// src/store/actions.js
export const actionTypes = {
  SET_LOADING: "SET_LOADING",
  SET_ERROR: "SET_ERROR",
  SET_INITIAL_DATA: "SET_INITIAL_DATA",
  UPDATE_HERO_DATA: "UPDATE_HERO_DATA",
  UPDATE_ABOUT_DATA: "UPDATE_ABOUT_DATA",
  UPDATE_PRODUCTS: "UPDATE_PRODUCTS",
  UPDATE_TESTIMONIALS: "UPDATE_TESTIMONIALS",
  UPDATE_FAQ: "UPDATE_FAQ",
  UPDATE_CONTACT: "UPDATE_CONTACT",
  UPDATE_QUERIES: "UPDATE_QUERIES",
};
